image: nginx:1.27-alpine
replicaCount: 1
containerPort: 80
service:
  type: ClusterIP
  port: 80
resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: 100m
    memory: 512Mi
ingress:
  enabled: true
  className: apisix
  hosts:
  - host: sample-service-app.example.internal
    paths:
    - path: /
      pathType: Prefix
